### PR TITLE
Site template tests

### LINKED ISSUE #268: Update Jest tests
Pushkin's basic experiment template issue [#37](https://github.com/pushkin-consortium/pushkin-exptemplates-basic/issues/37)

### LINKED ISSUE #319: Add overview to new monorepo to "Developer" section of docs
Something that explains (or points to a tutorial on) changesets, etc.

Basically, if somebody had never seen a monorepo, didn't know about changesets, etc., what would they need to read to make sense of things. 

Asking for a friend. :)

### LINKED ISSUE #341: have an option for install experiment that does all the available templates
We will want this to work when there is more than one available site template. This will greatly help in testing different changes and also for users who want to quickly try out all of the available experiments. The best way is to leave the `install site` alone and then have an option for the `install experiment` that does all the available templates

### LINKED ISSUE #345: Cookie sessions secret key security
The constructor for _../pushkin/packages/pushkin-api/src/api.js_ sets up a cookieSession with a hard coded secret key to prevent tampering, however we never overwrite it with a more secure key in any of the files for the pushkin project. This doesn't really make the secret key secret, so I propose, in _../pushkin/templates/sites/basic/src/pushkin/api/src/index.js_, we set a randomly generated secret key when calling the api constructor.

### PR DESCRIPTION
**Pull request by jessestorbeck**
This branch contains a number of recent development projects:

- Tests for the basic site template (which also ship to the user's site after installation)
- Test-related improvements to the CLI (installing site/exp templates without inquirer interactivity, installing all available exp templates with a single command)
- Reintroducing linting and some associated Babel tweaks
- Security-related updates

### CODE REVIEW

**Comment by jkhartshorne** [comment]
I installed a site. That went OK. Tried installing a basic experiment template and got this:

> jkhartshorne@MacBook-Air-345 temp % node ../pushkin/packages/pushkin-cli/build/index.js install experiment
> ? What do you want to call your experiment? myexp
> ? Where do you want to look for experiment templates? @pushkin-templates
> ? Which experiment template would you like to use? @pushkin-templates/exp-basic
> ? Which version would you like to use? (Recommended: 6.1.0) 6.1.0
> warning @pushkin-templates/exp-basic > jest-environment-jsdom > jsdom > abab@2.0.6: Use your platform's native atob() and btoa() methods instead
> warning @pushkin-templates/exp-basic > jest-environment-jsdom > jsdom > data-urls > abab@2.0.6: Use your platform's native atob() and btoa() methods instead
> warning @pushkin-templates/exp-basic > jest-environment-jsdom > jsdom > domexception@4.0.0: Use your platform's native DOMException instead
> node:internal/errors:983
>   const err = new Error(message);
>               ^
> 
> Error: Command failed: yalc publish
> /Users/jkhartshorne/.config/yarn/global/node_modules/cliui/build/index.cjs:293
> const wrap = require('wrap-ansi');
>              ^
> 
> Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/jkhartshorne/.config/yarn/global/node_modules/wrap-ansi/index.js from /Users/jkhartshorne/.config/yarn/global/node_modules/cliui/build/index.cjs not supported.
> Instead change the require of index.js in /Users/jkhartshorne/.config/yarn/global/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.
>     at Object.<anonymous> (/Users/jkhartshorne/.config/yarn/global/node_modules/cliui/build/index.cjs:293:14) {
>   code: 'ERR_REQUIRE_ESM'
> }
> 
> Node.js v22.3.0
> 
>     at genericNodeError (node:internal/errors:983:15)
>     at wrappedFn (node:internal/errors:537:14)
>     at ChildProcess.exithandler (node:child_process:421:12)
>     at ChildProcess.emit (node:events:520:28)
>     at maybeClose (node:internal/child_process:1105:16)
>     at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
>   code: 1,
>   killed: false,
>   signal: null,
>   cmd: 'yalc publish',
>   stdout: '',
>   stderr: '/Users/jkhartshorne/.config/yarn/global/node_modules/cliui/build/index.cjs:293\n' +
>     "const wrap = require('wrap-ansi');\n" +
>     '             ^\n' +
>     '\n' +
>     'Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/jkhartshorne/.config/yarn/global/node_modules/wrap-ansi/index.js from /Users/jkhartshorne/.config/yarn/global/node_modules/cliui/build/index.cjs not supported.\n' +
>     'Instead change the require of index.js in /Users/jkhartshorne/.config/yarn/global/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.\n' +
>     '    at Object.<anonymous> (/Users/jkhartshorne/.config/yarn/global/node_modules/cliui/build/index.cjs:293:14) {\n' +
>     "  code: 'ERR_REQUIRE_ESM'\n" +
>     '}\n' +
>     '\n' +
>     'Node.js v22.3.0\n'
> }
> 
> Node.js v22.3.0

**Comment by jkhartshorne** [comment]
OK that was probably because I had an old version of Pushkin installed.

**Comment by jkhartshorne** [comment]
`pushkin start` is not working for me. I get the following error:

> Something went wrong:
> node:internal/process/promises:389
>       new UnhandledPromiseRejection(reason);
>       ^
> 
> UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
>     at throwUnhandledRejectionsMode (node:internal/process/promises:389:7)
>     at processPromiseRejections (node:internal/process/promises:470:17)
>     at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
>   code: 'ERR_UNHANDLED_REJECTION'
> }
> 

I played around with trying to figure out what's causing that error, without much luck. I did ask Copilot to check to see if there were any missing try/catch statements in the code. It found these in prep/index.js:

> publishLocalPackage: Added catch blocks for nested promises.
> prepApi: Added handling for the promise returned by publishLocalPackage.
> prepWeb: Added error handling for fs.promises.copyFile.
> prep: Added await for async functions and proper error handling for promises.
> cleanWeb: Added await for fs.promises.writeFile.
> prepAPIWrapper: Converted to async and added proper error handling.
> prepWebWrapper: Converted to async and added proper error handling.

I'm not sure all those are actually something we want. But the point is that I can't figure out what's causing the error and it seems like there are multiple missing try/catch statements.

If you can't reproduce this error, can you please try putting in the try/catch statements anywhere they might be needed and I can try running again?

**Comment by jessestorbeck** [comment]
@jkhartshorne -- If the error you're getting is from `start`, there's only one place it could be coming from in the action handler for `start`:

```js
      try {
        await compose.upAll({
          cwd: path.join(process.cwd(), "pushkin"),
          config: "docker-compose.dev.yml",
          log: options.verbose,
          commandOptions: composeUpOptions,
        });
        console.log("Starting. You may not be able to load localhost for a minute or two.");
      } catch (e) {
        console.error("Something went wrong:");
        throw e;
      }
```

This seems like a Docker issue. Have you tried updating Docker Engine and/or resetting completely with `docker system prune -a`?

I don't expect there to be any compatibility issues if you're testing the CLI changes with previously published templates, but using the updated templates and helper packages is going to give you the best chance of success. The procedure would be:

```
node <build/path> install site --path <path/to/site/template> -v
node <build/path> install exp --all <path/to/all/exp/templates> -v
node <build/path> use-dev api client worker --path <path/to/all/packages> -v
node <build/path> prep -v
node <build/path> start -v
```

**Review by jkhartshorne — APPROVED** [review]
Looks good!

**Pull request merged**
