### PR TITLE
remove mention of pushkin-jspsych

### LINKED ISSUE #28: Docs: Improve explanations of pushkin repos in getPushkin.rst

### LINKED ISSUE #227: Remove discussion of pushkin-jspsych, since that's deprecated.

### PR DESCRIPTION
**Pull request by jessestorbeck**
Resolves #227, resolves #28

### CODE REVIEW

**Comment by jessestorbeck** [comment]
Resolves #28

**Review by jkhartshorne — CHANGES_REQUESTED** [review]
Please add the same information about 

```JSON
    "files": [
        "build/*",
        ".yalc"
    ]
```

for pushkin-worker. It's going to be the same issue.

**Comment by jessestorbeck** [comment]
The package.json in an experiment's pushkin-worker doesn't have the `files` property yet. So should they add: `"files": ["build/*", ".yalc"]` or just `"files": [".yalc"]`?

**Comment by jkhartshorne** [comment]
they should probably add: "files": ["build/*", ".yalc"]

Though you should mention that this hasn't been tested yet.

**Comment by jessestorbeck** [comment]
I've made the changes above, and I can probably add the section on local testing with the API, since I'm about to try that myself.

**Pull request merged**
