### PR TITLE
comment out setDockerHub (issue #89)

### PR DESCRIPTION
**Pull request by restmegan**

### CODE REVIEW

**Comment by jkhartshorne** [comment]
@restmegan what's the first commit in this pull request? It seems to be based on a very old pull request? Was that on purpose?

**Comment by restmegan** [comment]
That was me updating my forked repo with recent updates

**Comment by jkhartshorne** [comment]
@restmegan - are you sure? It has 4 commits, all from 2018.

**Comment by restmegan** [comment]
Yeah that's weird, I can try doing it from a branch of the original repo instead and open a new pull for that

**Comment by jkhartshorne** [comment]
OK. Sounds good.

**Pull request closed without merging**
