### PR TITLE
Gitbook update

### LINKED ISSUE #214: Copying terminal commands from documentation includes `$` characters
Using the built-in copy button, e.g., here....

image

... copies the text `$ pushkin install experiment`, which includes the `$`. Pasting this into the terminal doesn't work.

### PR DESCRIPTION
**Pull request by jessestorbeck**
These are mostly Halit's changes to FAQs and troubleshooting, but I fixed some typos and made minor changes to the advanced section.

### CODE REVIEW

**Comment by jkhartshorne** [comment]
Addresses https://github.com/pushkin-consortium/pushkin/issues/207

**Review by jkhartshorne — CHANGES_REQUESTED** [review]
Looks like FAQ.md is mostly empty. Is that intentional?

**Comment by Halogen7A** [comment]
Yes it is intentional, mainly because I was not sure what the answers would be to those questions. I can work on them a little more and think of other FAQs.

**Comment by jkhartshorne** [comment]
> Yes it is intentional, mainly because I was not sure what the answers would be to those questions. I can work on them a little more and think of other FAQs.

Can you please at least right `TBD` there in the meantime? And then post an issue to fill those things in. Assign me for now.

**Review by ayang21 — APPROVED** [review]
It would be helpful for 'docs-gitbook/advanced/troubleshooting-pushkin.md', when you say "and make sure that the docker images are cleaned out", that you tell the users how to clean out the images. Otherwise, I changed very little else.

**Comment by jessestorbeck** [comment]
fixes #214. #207 could stay open, since FAQ section should continue to be developed.

**Review by jkhartshorne — APPROVED** [review]

**Pull request merged**
