### PR TITLE
Update Node installation from v14 to v20

### PR DESCRIPTION
**Pull request by hzeng2**
Node v14 is outdated and was giving me trouble building the site during a recent Pushkin upgrade. I have changed it to [v20](https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions), which is the latest version so far.

### CODE REVIEW

**Review by jkhartshorne — CHANGES_REQUESTED** [review]
Suggest 20.2. Last week, 20.3 had some weird bugs on Docker. Unless someone can confirm that 20.3 absolutely does not cause problems, I say we stick with 20.2 until a higher version has been confirmed.

**Comment by hzeng2** [comment]
@jkhartshorne -- I wasn't able to specify the Node.js version when installing it. But it seems the commands take care of it. It installs v20.2.0 automatically. I tried typing `20.2` and `20.2.0`. The both are not valid links. Please see below:
image
image

I then used the `20.x` command to install again. I can confirm that it installed v20.2.0 successfully.
image
`...`
`...`
`...`
image

Do you think we can use the last commit? Or should I add a few texts accompanying the commands specifying that users should use v20.2.0?

**Comment by jkhartshorne** [comment]
That seems overly complex. 

Do these instructions work for you? https://www.geeksforgeeks.org/how-
to-install-the-previous-version-of-node-js-and-npm/

--
Sent with HEY <https://hey.com/sent>

**Comment by hzeng2** [comment]
@jkhartshorne -- No. Unfortunately the commands in the link didn't work:

image
And here is the log:
[2023-06-21T07_50_07_914Z-debug-0.log.txt](https://github.com/pushkin-consortium/pushkin/files/11815083/2023-06-21T07_50_07_914Z-debug-0.log.txt)

I did some looking around and discovered that installing nvm and then using nvm to install node might be the method we want to use. Please see the new commit.

**Comment by jkhartshorne** [comment]
The new commit looks good to me, but I don't have a Windows machine. Can someone else who has one please check that this works for them (it successfully installs the right version of Node) and, if so, approve the merge?

@Halogen7A @jessestorbeck @ayang21

**Review by jkhartshorne — APPROVED** [review]

**Comment by hzeng2** [comment]
> The new commit looks good to me, but I don't have a Windows machine. Can someone else who has one please check that this works for them (it successfully installs the right version of Node) and, if so, approve the merge?
> 
> @Halogen7A @jessestorbeck @ayang21

Just FYI, the new commit refers to https://github.com/pushkin-consortium/pushkin/pull/210/commits/b9d2195af2beff66e23b1c63f2482648adb9bd79.

**Review by ayang21 — APPROVED** [review]
Worked great for me, but maybe note that you have to restart instance if you just downloaded nvm

**Comment by hzeng2** [comment]
> Worked great for me, but maybe note that you have to restart instance if you just downloaded nvm

Great suggestion! I have made changes according to it in this pull request #212.

**Pull request merged**
